name: Release app-a

concurrency:
  group: release-app-a

on:
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy app-a to production
    runs-on: ubuntu-latest
    environment:
      name: production-app-a
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sleep 60
